METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.002
  weight_decay: 0.0001
  milestones: [80]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    device: None 
    num_nodes: 207
    in_dim: 1
    out_dim: 12
    adj_path: "../data/METRLA/adj_mx.pkl"
    adj_type: "doubletransition"
    dropout: 0.3
    gcn_bool: True
    addaptadj: False
    aptinit: null
    node_emb_file: "../data/METRLA/spatial_embeddings.npz"
    tod_embedding_dim: 24
    dow_embedding_dim: 7
    node_embedding_dim: 64
    learner_hidden_dim: 128
    z_dim: 64
    add_meta_adj: False
    add_meta_att: True

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [50]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 325
    in_dim: 2
    out_dim: 12
    adj_path: "../data/PEMSBAY/adj_mx_bay.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [115]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 358
    in_dim: 2
    out_dim: 12
    adj_path: "../data/PEMS03/adj_PEMS03_distance.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [175]
  early_stop: 15
  clip_grad: False
  batch_size: 64
  max_epochs: 500
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 307
    in_dim: 2
    out_dim: 12
    adj_path: "../data/PEMS04/adj_PEMS04_distance.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [108]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 883
    in_dim: 2
    out_dim: 12
    adj_path: "../data/PEMS07/adj_PEMS07_distance.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [168]
  early_stop: 15
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 170
    in_dim: 2
    out_dim: 12
    adj_path: "../data/PEMS08/adj_PEMS08_distance.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null
    