METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [40]
  lr_decay_rate: 0.1
  batch_size: 64
  max_epochs: 200
  early_stop: 20
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 207
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 12
    tod_embedding_dim: 12
    dow_embedding_dim: 12
    adaptive_embedding_dim: 60
    feed_forward_dim: 128
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [10, 50]
  batch_size: 32
  max_epochs: 200
  early_stop: 20
  use_cl: False

  model_args:
    num_nodes: 325
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 12
    tod_embedding_dim: 12
    dow_embedding_dim: 12
    adaptive_embedding_dim: 60
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [10, 30]
  batch_size: 64
  max_epochs: 200
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 358
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 12
    tod_embedding_dim: 12
    dow_embedding_dim: 12
    adaptive_embedding_dim: 60
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [10, 30]
  batch_size: 64
  max_epochs: 200
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 307
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 12
    tod_embedding_dim: 12
    dow_embedding_dim: 12
    adaptive_embedding_dim: 60
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [10, 30]
  batch_size: 64
  max_epochs: 200
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 883
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 12
    tod_embedding_dim: 12
    dow_embedding_dim: 12
    adaptive_embedding_dim: 60
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.002
  weight_decay: 0.0001
  milestones: [1, 50, 80]
  lr_decay_rate: 0.5
  batch_size: 64
  max_epochs: 200
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 170
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 12
    tod_embedding_dim: 12
    dow_embedding_dim: 12
    adaptive_embedding_dim: 60
    feed_forward_dim: 96
    num_heads: 4
    num_layers: 3
    dropout: 0.1
